<template>
    <nav>
      <div class="nav-img">
        <img src="../assets/Vector.png" alt="" />
        <h1>Game<span>Hub</span></h1>
      </div>
      <ul class="Nav-links" >
        <li class="nav-link-item" v-for="link in links" :key="link.name">
          <a :href="link.link">{{ link.name }}</a>
        </li>
      </ul>
      <a href="" id="faq">Get started</a>
    </nav>
  </template>
  
  <script>
  export default {
    data() {
      return {
        links: [
          { name: "Home", link: "#" },
          { name: "About", link: "#" },
          { name: "Contact", link: "#" },
          { name: "Article", link: "#" },
          { name: "FAQ", link: "#" },
        ],
      };
    },
  };
  </script>
  
<style scoped>
nav{
    margin: 2.5rem 4.5rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: rgba(25, 37, 10, 3%);
    padding: 10px;
    border-radius: 10px;
    flex-wrap: wrap;
}
.nav-img{
    display: flex;
    gap: .625rem;
    align-items: center;
    justify-content: center;

}
.Nav-links{
    list-style: none;
    text-decoration: none;
    display: flex;
    gap: 2rem;
    align-items: center;
    justify-content: center;

}
.Nav-links a{
text-decoration: none;
color: #19250A;
opacity: 0.7;
transition: all 0.25s ease;

}
.nav-link-item:hover a{
color: #97F123;
opacity:1;
-webkit-animation: text-shadow-drop-tr 0.6s both;
	        animation: text-shadow-drop-tr 0.6s both;
}
span{
    color: #97F123;
}
#faq{
    color: #fff;
    padding: 8px 20px;
    background-color: #97F123;
    border-radius:12px ;
    font-size: 18px;
    font-weight: 700;
    text-decoration: none;
transition: all 0.12s linear;
}
#faq:hover{
	-webkit-animation: wobble-hor-bottom 0.1s both;
	        animation: wobble-hor-bottom 0.1s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-12-3 21:2:16
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-bottom
 * ----------------------------------------
 */
 @-webkit-keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
            transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
            transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
            transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
            transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
            transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
            transform: translateX(-6px) rotate(-1.2deg);
  }
}
@keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
            transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
            transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
            transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
            transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
            transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
            transform: translateX(-6px) rotate(-1.2deg);
  }
}





/* ----------------------------------------------
 * Generated by Animista on 2023-12-3 21:3:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * @animation text-shadow-drop-tr
 * ----------------------------------------
 */
 @-webkit-keyframes text-shadow-drop-tr {
  0% {
    text-shadow: 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    text-shadow: 6px -6px 18px rgba(0, 0, 0, 0.35);
  }
}
@keyframes text-shadow-drop-tr {
  0% {
    text-shadow: 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    text-shadow: 6px -6px 18px rgba(0, 0, 0, 0.35);
  }
}


</style>
